name: check

on:
  push:
    branches: [master, main]
  pull_request:
  merge_group:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nix-fast-build:
    name: nix-fast-build
    runs-on: ubuntu-24.04
    permissions:
      contents: read # リポジトリコンテンツの読み取り
      id-token: write # niks3 OIDC認証
    timeout-minutes: 120 # キャッシュがヒットしなくてGHCのビルドなどをすると時間がかかるため、タイムアウトを長めに設定。
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: ncaq/nix-composite-action@5ac23c3150c5fdeb2a5f665e288c09bf1d59870a # v1.1.2
        with:
          extra-nix-config: |
            sandbox = relaxed
          cachix-auth-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix run '.#nix-fast-build' -- --option eval-cache false --option sandbox relaxed --no-link --skip-cached --no-nom
